### ISSUE TITLE
非RPC消息的Handler 

### ISSUE THREAD

**Issue by ACrsm** [Bian-Sh/ET-Network-Module#2]
请问生成的非RPC消息的Handler 有什么作用？Example 中看起来直接使用监听的方式实现了回调。

**Comment by Bian-Sh** [comment]
好问题哎，之前考虑的无脑预防scriptingbackends 为 il2cpp 时的代码裁剪，你可以按自己的想法精简成自己想要的样子

**Comment by ACrsm** [comment]
感谢提供拆分的客户端，我也是想单独使用ET6.0的服务器，客户端就用自己熟悉的了。
